'use strict';
module.exports = {
  async getNetwork({homey}) {return homey.app.network.list();},
  async saveNetwork({homey,body}) {return homey.app.network.save(body.target);},
  async removeNetwork({homey,body}) {return homey.app.removeNetworkTarget(body.id);},
  async testNetwork({homey,body}) {return homey.app.jobs.start(()=>homey.app.network.test(body.id));},
  async backupNetwork({homey,body}) {return homey.app.jobs.start(()=>homey.app.network.backup(body.id));},
  async getAppInfo({ homey }) { return homey.app.getAppInfo(); },
  async exportBackup({ homey }) { return homey.app.exportBackup(); },
  async restorePlan({ homey, body }) { return homey.app.buildRestorePlan(body.backup); },
  async getRestoreAuth({ homey }) { return homey.app.getRestoreAuthStatus(); },
  async saveRestoreAuth({ homey, body }) { return homey.app.saveRestoreAuthToken(body.token || ''); },
  async testRestoreAuth({ homey }) { return homey.app.testRestoreAuth(); },
  async restoreRun({ homey, body }) { return homey.app.restoreBackup(body.backup, body.confirm, body.selection || {}); },
  async getWebdav({ homey }) { return homey.app.getWebdavTargetsForUi(); },
  async saveWebdav({ homey, body }) { return homey.app.saveWebdavTargets(body.config); },
  async testWebdav({ homey, body }) { return homey.app.testWebdav(body.targetId); },
  async uploadWebdav({ homey, body }) { return homey.app.runScheduleNow(body.targetId); },
  async getSchedule({ homey }) { return homey.app.getSchedule(); },
  async saveSchedule({ homey, body }) { return homey.app.saveSchedule(body.config); },
  async runScheduleNow({ homey, body }) { return homey.app.runScheduleNow(body.targetId || ''); },
  async saveLanguage({homey,body}) {return homey.app.saveLanguage(body.language);},
  async notificationUsers({homey}) {return homey.app.notificationUsers();},
  async startTransfer({homey,body}) {return homey.app.startBackupTransfer(body.bytes,body.kind);},
  async appendTransfer({homey,body}) {return homey.app.appendBackupTransfer(body);},
  async finishTransfer({homey,body}) {return homey.app.finishBackupTransfer(body.id);},
  async readTransfer({homey,body}) {return homey.app.transfers.read(body.id,body.offset);},
  async releaseTransfer({homey,body}) {return homey.app.transfers.release(body.id);},
  async prepareExport({homey}) {return homey.app.startExport();},
  async stagedRestorePlan({homey,body}) {return homey.app.startRestorePlan(body.id);},
  async stagedRestoreRun({homey,body}) {return homey.app.startRestoreRun(body.id,body.confirm,body.selectionId);},
  async getJob({homey,body}) {return homey.app.jobs.get(body.id);},
  async releaseJob({homey,body}) {return homey.app.jobs.release(body.id);},
};
